CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY ,
    username VARCHAR(255) NOT NULL,
    totpSecret VARCHAR(255),
    backupCodes VARCHAR(255),
    password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS task (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    details VARCHAR(255)
);
